# Generated by Django 5.2.4 on 2025-08-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0002_remove_equipo_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
