# Generated by Django 5.2.4 on 2025-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0003_jugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='ganador',
            field=models.BooleanField(default=False),
        ),
    ]
