# Generated by Django 5.2.4 on 2025-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0004_apuesta_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('arbitro', 'Árbitro'), ('jugador', 'Jugador'), ('apostador', 'Apostador')], max_length=10),
        ),
    ]
