# Generated by Django 5.2.4 on 2025-08-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('datos_pago', models.TextField(blank=True, null=True)),
                ('fecha_recarga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
