# Generated by Django 5.2.4 on 2025-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0006_recargasaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
