# Generated by Django 5.2.4 on 2025-08-07 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0007_usuario_saldo_real'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apuesta',
            options={'verbose_name': 'Apuesta', 'verbose_name_plural': 'Apuestas'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('arbitro', 'Árbitro'), ('jugador', 'Jugador'), ('apostador', 'Apostador')], default='apostador', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditoriaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_anterior', models.CharField(choices=[('admin', 'Administrador'), ('arbitro', 'Árbitro'), ('jugador', 'Jugador'), ('apostador', 'Apostador')], max_length=20)),
                ('rol_nuevo', models.CharField(choices=[('admin', 'Administrador'), ('arbitro', 'Árbitro'), ('jugador', 'Jugador'), ('apostador', 'Apostador')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
