# Generated by Django 5.2.4 on 2025-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0008_alter_apuesta_options_alter_usuario_rol_auditoriarol'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
    ]
