# Generated by Django 5.2.4 on 2025-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0009_jugador_asistencias_jugador_biografia_jugador_goles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='correo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='numero_camiseta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
