# Generated by Django 5.2.4 on 2025-08-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0010_remove_jugador_correo_jugador_numero_camiseta'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_partido', to='mitorneo.partido'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
