# Generated by Django 5.2.4 on 2025-08-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0011_apuesta_partido_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='partido',
        ),
        migrations.AddField(
            model_name='partido',
            name='porcentaje_victoria_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='porcentaje_victoria_visitante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('gol', 'Gol'), ('asistencia', 'Asistencia')], max_length=20)),
                ('minuto', models.IntegerField()),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_realizadas', to='mitorneo.jugador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_equipo', to='mitorneo.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_anotados', to='mitorneo.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='mitorneo.partido')),
            ],
        ),
    ]
