# Generated by Django 5.2.4 on 2025-08-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0012_remove_apuesta_partido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='goles_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='porcentaje_victoria_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='porcentaje_victoria_visitante',
        ),
        migrations.DeleteModel(
            name='EventoPartido',
        ),
    ]
