# Generated by Django 5.2.4 on 2025-08-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0013_remove_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.CharField(default='programado', max_length=20),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
