# Generated by Django 5.2.4 on 2025-08-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0014_partido_estado_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='estado',
        ),
        migrations.AddField(
            model_name='apuesta',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_partido', to='mitorneo.partido'),
        ),
    ]
