# Generated by Django 5.2.4 on 2025-08-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0015_remove_partido_estado_apuesta_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='mitorneo.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='simulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mitorneo.arbitro'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
