# Generated by Django 5.2.4 on 2025-08-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitorneo', '0016_partido_ganador_partido_resultado_partido_simulado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriarol',
            name='cambiado_por',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='asistencias',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='goles',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='partidos_jugados',
        ),
        migrations.AddField(
            model_name='equipo',
            name='entrenador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_equipo', to='mitorneo.equipo'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='mitorneo.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nivel',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
